#!/bin/sh

if [ $# -eq 0 ]; then
  echo "No arguments supplied"
  exit 1
fi

if [ -z "$1" ]; then
  echo "No subdomain supplied"
  exit 1
fi

if [ -z "$2" ]; then
  echo "No port supplied"
  exit 1
fi

ssh -R $1:80:localhost:$2 serveo.net
